from setuptools import setup


req_list = []
with open('requirements.txt', mode='r') as f:
    for line in f:
        req_list.append(line)

setup(
    name='eda-report-parser',
    author='Maksymilian Graczyk',
    version='0.1',
    description='Parser for reports generated by EDA tools',
    packages=['edaparser'],
    install_requires=req_list,
    entry_points={
        'console_scripts': ['reporthtml=edaparser.reporthtml:main']
    }
)
